In [2]:
## 텐서 초기화: 텐서에 특정 값을 채워서 생성하는 것

import torch
import numpy as np

In [ ]:
## 초기화 되지 않은 텐서 -> 특정값이 채워지지 않은 상태로 생성하는 것

tensor=torch.empty(4, 2)
print(tensor)

tensor([[-3.0460e+23,  1.6381e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])


In [ ]:
## 상수로 초기화 된 텐서
b=torch.zeros(2,4, dtype=torch.long)    # 데이터 타입 지정 가능
a=torch.ones(2,4)

print(a)
print(b)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])


In [17]:
## 무작위로 초기화된 텐서
a=torch.rand(3,4)    # 0~1 값으로 초기화
print(a)

b=torch.randn(3,4)    # 표준 정규분포에서 무작위로 초기화
print(b)

tensor([[0.8949, 0.4159, 0.6428, 0.2284],
        [0.2962, 0.4400, 0.4215, 0.2381],
        [0.1856, 0.4792, 0.2022, 0.9433]])
tensor([[ 1.6979,  1.5536, -0.1911,  1.6500],
        [-0.8590,  1.2366,  0.9584, -0.3660],
        [ 0.8572,  1.9465, -0.4444,  1.4646]])


In [18]:
## 직접 입력한 값으로 초기화

a=torch.tensor([1,2,3])
print(a)


tensor([1, 2, 3])


In [ ]:
## numpy 배열로부터 초기화

np_array=np.array([1,2,3])

# 넘파이 텐서 전환
a=torch.from_numpy(np_array)
print(a)

#텐서 넘파이 전환
b=a.numpy()
print(b)
print(type(b))

# 변환하면 얕은 복사가 됨
b[2]=100
print(a)




tensor([1, 2, 3])
[1 2 3]
<class 'numpy.ndarray'>
tensor([  1,   2, 100])


In [28]:
## 특정 텐서와 같은 사이즈의 텐서에 무작위로 값을 채움

a=torch.ones(2,4, dtype=torch.long)
b=torch.rand_like(a, dtype=torch.float)
b_2=torch.randn_like(a, dtype=torch.float)
c=torch.zeros_like(a, dtype=torch.float)

print(a)
print(b)
print(b_2)
print(c)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0.5765, 0.6020, 0.5316, 0.5374],
        [0.0801, 0.1662, 0.1561, 0.0423]])
tensor([[ 0.0842, -0.3377,  0.0495,  0.1695],
        [ 0.4602, -0.8214, -0.1844, -1.0510]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [22]:
## 텐서의 속성

a=torch.rand(3,4)    # 0~1 값으로 초기화
print(a)

print(a.size())
print(a.shape)

print(a.dtype)    # 기본 float32

print(a.device)    # 쓰고 있는 부품 출력 (cpu or gpu)

tensor([[0.6037, 0.0798, 0.3070, 0.0705],
        [0.2706, 0.7784, 0.2067, 0.1677],
        [0.2671, 0.3285, 0.8809, 0.0819]])
torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
cpu


In [13]:
## 특정 타입의 텐서 생성

a=torch.rand(3,4, dtype=torch.float64)
print(a.dtype)

b=torch.FloatTensor([1,2,3])
print(b)
print(b.dtype)

c=torch.IntTensor([1,2,3])
print(c)
print(c.dtype)


torch.float64
tensor([1., 2., 3.])
torch.float32
tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [19]:
## 데이터 타입 캐스팅(형 변환)

# float -> int
b=torch.FloatTensor([1,2,3])
print(b.int())

# int -> float
c=torch.IntTensor([1,2,3])
print(c.float())


tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


In [ ]:
## 다차원 텐서 표현

# tensor(scalar): 하나의 값을 가지고 있는 텐서
t0=torch.tensor(100)
print(t0.ndim)     # 차원 출력
print(t0.shape)     # 사이즈 출력
print(t0)


# 1차원 텐서(vector): 값들을 저장하고 있는 리스트와 유사한 테서
t1=torch.tensor([1,2])
print(t1.ndim)
print(t1.shape)
print(t1)


# 2차원 텐서(matrix): 행렬과 같은 모양으로 두개의 축이 존재
t2=torch.tensor([[1,2],[3,4]])
print(t2.ndim)
print(t2.shape)
print(t2)


# 3차원 텐서(cube): 큐브와 같은 형태로 세 개의 축이 존재
t3=torch.tensor([
    [[1,2,3],[3,4,5]],
    [[0,1,2],[2,3,4]]
    ])
print(t3.ndim)
print(t3.shape)
print(t3)


# 4차원 텐서
t4=torch.rand(3,2,3,2)
print(t4.ndim)
print(t4.shape)
print(t4)

0
torch.Size([])
tensor(100)
1
torch.Size([2])
tensor([1, 2])
2
torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])
3
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[0, 1, 2],
         [2, 3, 4]]])
4
torch.Size([3, 2, 3, 2])
tensor([[[[0.9246, 0.9426],
          [0.9976, 0.9728],
          [0.1879, 0.9535]],

         [[0.9858, 0.3144],
          [0.1702, 0.5900],
          [0.4494, 0.7390]]],


        [[[0.1141, 0.3003],
          [0.9022, 0.0599],
          [0.0179, 0.3026]],

         [[0.5279, 0.3901],
          [0.6495, 0.3939],
          [0.9028, 0.9205]]],


        [[[0.9872, 0.2471],
          [0.4042, 0.5955],
          [0.3001, 0.6831]],

         [[0.6412, 0.4894],
          [0.8757, 0.2945],
          [0.5101, 0.5544]]]])
