In [1]:
import torch
import numpy as np

In [ ]:
## 산술 연산
a=torch.rand(2,2)
print(a)

a2=a*2
print(a2)

a3=a+1
print(a3)

tensor([[0.8886, 0.1676],
        [0.2232, 0.3289]])
tensor([[1.7772, 0.3352],
        [0.4464, 0.6577]])
tensor([[1.8886, 1.1676],
        [1.2232, 1.3289]])
tensor([[0.5858, 0.5111],
        [0.6365, 0.6291]])
tensor([[1.4744, 0.6787],
        [0.8597, 0.9579]])


In [ ]:
# 더하기

a=torch.rand(2,2)
b=torch.rand(2,2)

print(a)
print(b)
print(a+b)

add=torch.add(a,b)
print(add)

tensor([[0.5449, 0.5382],
        [0.0969, 0.7987]])
tensor([[0.1061, 0.4682],
        [0.9109, 0.4487]])
tensor([[0.6510, 1.0064],
        [1.0078, 1.2473]])
tensor([[0.6510, 1.0064],
        [1.0078, 1.2473]])


In [ ]:
add=torch.add(a,b)
print(add)

## in_place 바꿔치기 연산

b.add_(a)
print(b)

tensor([[1.0471, 1.7450],
        [0.4839, 1.2584]])
tensor([[1.0471, 1.7450],
        [0.4839, 1.2584]])


In [22]:
# 빼기

a=torch.rand(2,2)
b=torch.rand(2,2)

sub=torch.sub(a,b)
print(a-b)
print(sub)

tensor([[-0.3307, -0.3297],
        [-0.4722,  0.3657]])
tensor([[-0.3307, -0.3297],
        [-0.4722,  0.3657]])


In [24]:
# 곱하기

a=torch.rand(2,2)
b=torch.rand(2,2)

mul=torch.mul(a,b)
print(a*b)
print(mul)


tensor([[0.0571, 0.5181],
        [0.1382, 0.7258]])
tensor([[0.0571, 0.5181],
        [0.1382, 0.7258]])


In [30]:
# 나누기

a=torch.rand(2,2)
b=torch.rand(2,2)

div=torch.div(a,b)
print(a/b)
print(div)


tensor([[ 0.4762,  1.3661],
        [ 0.2075, 32.9311]])
tensor([[ 0.4762,  1.3661],
        [ 0.2075, 32.9311]])
