In [1]:
import torch
import numpy as np

In [ ]:
## 산술 연산
a=torch.rand(2,2)
print(a)

a2=a*2
print(a2)

a3=a+1
print(a3)

tensor([[0.8886, 0.1676],
        [0.2232, 0.3289]])
tensor([[1.7772, 0.3352],
        [0.4464, 0.6577]])
tensor([[1.8886, 1.1676],
        [1.2232, 1.3289]])
tensor([[0.5858, 0.5111],
        [0.6365, 0.6291]])
tensor([[1.4744, 0.6787],
        [0.8597, 0.9579]])


In [ ]:
# 더하기

a=torch.rand(2,2)
b=torch.rand(2,2)

print(a)
print(b)
print(a+b)

add=torch.add(a,b)
print(add)

tensor([[0.5449, 0.5382],
        [0.0969, 0.7987]])
tensor([[0.1061, 0.4682],
        [0.9109, 0.4487]])
tensor([[0.6510, 1.0064],
        [1.0078, 1.2473]])
tensor([[0.6510, 1.0064],
        [1.0078, 1.2473]])


In [ ]:
add=torch.add(a,b)
print(add)

## in_place 바꿔치기 연산

b.add_(a)
print(b)

tensor([[1.0471, 1.7450],
        [0.4839, 1.2584]])
tensor([[1.0471, 1.7450],
        [0.4839, 1.2584]])


In [22]:
# 빼기

a=torch.rand(2,2)
b=torch.rand(2,2)

sub=torch.sub(a,b)
print(a-b)
print(sub)

tensor([[-0.3307, -0.3297],
        [-0.4722,  0.3657]])
tensor([[-0.3307, -0.3297],
        [-0.4722,  0.3657]])


In [2]:
# 곱하기

a=torch.rand(2,2)
b=torch.rand(2,2)

mul=torch.mul(a,b)
print(a*b)
print(mul)


tensor([[0.0983, 0.0970],
        [0.8214, 0.5094]])
tensor([[0.0983, 0.0970],
        [0.8214, 0.5094]])


In [ ]:
# 나누기

a=torch.rand(2,2)
b=torch.rand(2,2)

div=torch.div(a,b)
print(a/b)
print(div)

tensor([[0.8609, 1.6490],
        [0.4349, 1.0068]])
tensor([[0.8609, 1.6490],
        [0.4349, 1.0068]])


In [87]:
# math 모듈

a=torch.tensor(-10)
print('절대값', torch.abs(a))


b=torch.tensor(3.6)
print('올림', torch.ceil(a))
print('올림', torch.round(a))
print('내림', torch.floor(a))


c=torch.randn(2,2)
print('클램프', torch.clamp(c, -0.5, 0.5))   # 값 or 행렬, 최대값, 최소값    값이 최대값과 최소값 사이에 없다면 최대값 혹은 최소값으로 설정

절대값 tensor(10)
올림 tensor(-10)
올림 tensor(-10)
내림 tensor(-10)
클램프 tensor([[-0.0517,  0.2633],
        [-0.2467, -0.5000]])


In [ ]:
# 각종 연산

a=torch.randn(2,2)
b=torch.tensor([[1,2],[3,4]])
c=torch.tensor([1,1,1,1,2,2,2,3,3,3,4,4,4,4,4,5])

print('최소값', torch.min(a))
print('최대값', torch.max(a))
print('평균', torch.mean(a))
print('표준편차', torch.std(a))

print('모든 원소의 합', torch.sum(a))
print('모든 원소의 합', torch.sum(b, dim=0))    # 0: 열, 1: 행

print('모든 원소의 곱', torch.prod(b))

print('중복값 제거', torch.unique(c))

최소값 tensor(-1.3897)
최대값 tensor(0.3131)
평균 tensor(-0.5925)
표준편차 tensor(0.7149)
모든 원소의 합 tensor(-2.3699)
모든 원소의 합 tensor([4, 6])
모든 원소의 곱 tensor(24)
중복값 제거 tensor([1, 2, 3, 4, 5])


In [ ]:
## 내적 연산(dot product) : 행렬 연산

x=torch.tensor([[1,2],[3,4]])
y=torch.tensor([[5,6],[7,8]])

result=torch.matmul(x, y)
print(result)

tensor([[19, 22],
        [43, 50]])
