In [2]:
## tensor의 조작

import torch
import numpy as np

In [ ]:
## 인덱싱, 슬라이싱

a=torch.tensor([[1,2],[3,4]])

print(a[0,1])
print(a[0,:])

a=torch.tensor([1,2,3,4,5])
print(a[-2:-1])


# 조건부
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a[a>5])
print(a[a%2==0])


# 인덱싱의 인덱싱
print(a[[0,1],[1,2]])               #a[0,1], a[1,2]를 불러옴

tensor(2)
tensor([1, 2])
tensor([4])
tensor([6, 7, 8, 9])
tensor([2, 4, 6, 8])


tensor([2, 6])

In [81]:
## 텐서의 크기, 모양 변경

t=torch.rand(4,5)
print(t)

x=t.view(5,4)
print(x)

y=t.view(10,2)
print(y)

tensor([[0.5392, 0.6905, 0.0715, 0.5802, 0.3574],
        [0.4564, 0.6391, 0.3270, 0.5542, 0.5138],
        [0.4390, 0.1952, 0.0746, 0.0900, 0.3367],
        [0.9370, 0.3408, 0.6305, 0.6427, 0.8568]])
tensor([[0.5392, 0.6905, 0.0715, 0.5802],
        [0.3574, 0.4564, 0.6391, 0.3270],
        [0.5542, 0.5138, 0.4390, 0.1952],
        [0.0746, 0.0900, 0.3367, 0.9370],
        [0.3408, 0.6305, 0.6427, 0.8568]])
tensor([[0.5392, 0.6905],
        [0.0715, 0.5802],
        [0.3574, 0.4564],
        [0.6391, 0.3270],
        [0.5542, 0.5138],
        [0.4390, 0.1952],
        [0.0746, 0.0900],
        [0.3367, 0.9370],
        [0.3408, 0.6305],
        [0.6427, 0.8568]])


In [27]:
## 텐서의 숫자가 얻기 (스칼라 값)

x=torch.tensor(10)
print(x.item())

y=torch.rand(1)
print(y)
print(y.item())


10
tensor([0.1444])
0.1444305181503296


In [79]:
# 차원 축소와 증가

'''
torch.squeeze(): 크기가 1인 차원을 축소함(없앤다)
torch.unsqueeze(): 지정한 위치에 새로운 차원을 생성
'''

# 차원 축소
t=torch.rand(1,3,3,1)
print(t.shape)

ts=torch.squeeze(t)
print(ts.shape)


# 차원 생성
t=torch.rand(3,3,3)
print(t.shape)

ts=torch.unsqueeze(t,0)     # 텐서, 위치
print(ts.shape)

torch.Size([1, 3, 3, 1])
torch.Size([3, 3])
torch.Size([3, 3, 3])
torch.Size([1, 3, 3, 3])


In [ ]:
## 텐서간 결합
'''
torch.stack(): 동일한 형식의 텐서를 새롭게 그룹화한다. (새로운 차원이 생성)
torch.cat(): 텐서를 하나로 결합(차원을 유지)
'''

# stack
a=torch.tensor([[1,2],[3,4]])     # 2*2
b=torch.tensor([[5,6],[7,8]])     # 2*2
c=torch.stack([a,b])

print(c)
print(c.shape)    # 2*2*2

# cat
a=torch.tensor([[1,2],[3,4]])     # 2*2
b=torch.tensor([[5,6],[7,8]])     # 2*2
b_2=torch.tensor([[5,6],[7,8],[9,10]])     # 3*2
c=torch.cat([a,b], dim=1)    # 0: 열을 고정하여 합, 1: 행을 고정하여 합
c_2=torch.cat([a,b_2], dim=0)

print(c)
print(c.shape)    # 2*4

print(c_2)
print(c_2.shape)    # 5*2

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
torch.Size([2, 4])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])
torch.Size([5, 2])


In [ ]:
## 텐서 나누기
'''
torch.chunk(): 텐서를 몇개로 나눌지를 지정하여 나눔, 나누어 떨어지지 않으면 마지막 조각은 크기가 다름
torch.split(): 텐서의 지정된 크기를 기준으로 나누기
'''

# chunk
t=torch.rand(5,3)
print(t)

a,b,c=torch.chunk(t,3, dim=0)     # 탠서, 나눌 값, 0: 행기준으로 쪼개기 1: 열기준으로 쪼개기
print(a)
print(b)
print(c)



tensor([[0.4463, 0.4957, 0.0599],
        [0.4870, 0.7192, 0.5215],
        [0.9501, 0.0390, 0.1254],
        [0.6438, 0.5919, 0.1780],
        [0.4634, 0.4419, 0.8537]])
tensor([[0.4463, 0.4957, 0.0599],
        [0.4870, 0.7192, 0.5215]])
tensor([[0.9501, 0.0390, 0.1254],
        [0.6438, 0.5919, 0.1780]])
tensor([[0.4634, 0.4419, 0.8537]])


In [83]:
# split
t=torch.rand(3,6)
print(t)

a,b=torch.split(t, 4, dim=1)      # 0: 행 기준으로 나누기,  1: 열 기준으로 나누기
print(a)
print(b)

t_1=torch.tensor([[1,2,3,4,5],[1,2,3,4,5]])
print(t_1)
c,d,e=torch.split(t_1, [2,2,1], dim=1)      # 0: 행 기준으로 나누기,  1: 열 기준으로 나누기
print(c)
print(d)
print(e)

tensor([[0.7615, 0.4731, 0.0051, 0.4392, 0.7648, 0.4678],
        [0.1629, 0.2491, 0.8901, 0.7847, 0.4168, 0.0211],
        [0.8969, 0.0027, 0.4842, 0.3437, 0.4616, 0.7461]])
tensor([[0.7615, 0.4731, 0.0051, 0.4392],
        [0.1629, 0.2491, 0.8901, 0.7847],
        [0.8969, 0.0027, 0.4842, 0.3437]])
tensor([[0.7648, 0.4678],
        [0.4168, 0.0211],
        [0.4616, 0.7461]])
tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])
tensor([[1, 2],
        [1, 2]])
tensor([[3, 4],
        [3, 4]])
tensor([[5],
        [5]])
