## PyTorch Quiz 1 : Tensor 초기화

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [ ]:
import torch

a=torch.empty(3,4)
print(a)

tensor([[4.7388e-38, 1.7670e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [ ]:
import torch

a=torch.zeros(2,5,3, dtype=torch.double)
print(a)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)


### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [ ]:
import torch

a=torch.ones(4,4, dtype=torch.int)
print(a)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [ ]:
import torch

a=torch.rand(3,3)
print(a)

tensor([[0.9353, 0.5689, 0.8295],
        [0.5159, 0.7479, 0.1440],
        [0.0698, 0.3850, 0.4717]])


### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [ ]:
import torch

a=torch.tensor([[1,2,3],[4,5,6]])
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]])


### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 값을 모두 0으로 바꿔보세요. 

In [ ]:
import torch

a=torch.randn(2,2)
print(a)

b=torch.zeros_like(a)
print(b)

tensor([[-1.5644, -0.9535],
        [ 0.7890,  1.4887]])
tensor([[0., 0.],
        [0., 0.]])
