## PyTorch Quiz 2 : 연산

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [3]:
import torch

a=torch.tensor([2,4,6])

b=a+5
print(b)

c=a-3
print(c)

tensor([ 7,  9, 11])
tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [5]:
a=torch.rand(3,3)
b=torch.rand(3,3)

print(torch.add(a,b))
print(torch.sub(a,b))
print(torch.mul(a,b))
print(torch.div(a,b))

tensor([[0.6517, 1.2194, 0.5937],
        [1.6085, 1.5504, 1.4215],
        [0.7979, 0.6362, 0.6772]])
tensor([[-0.3736,  0.2182, -0.5431],
        [-0.2596, -0.0335,  0.4902],
        [ 0.5862, -0.2501, -0.5634]])
tensor([[0.0713, 0.3598, 0.0144],
        [0.6300, 0.6007, 0.4451],
        [0.0732, 0.0855, 0.0353]])
tensor([[0.2713, 1.4359, 0.0445],
        [0.7220, 0.9577, 2.0526],
        [6.5402, 0.4355, 0.0917]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [4]:
a=torch.tensor([[1,2,3],[4,5,6]])          # 2*3
b=torch.tensor([[7,8],[9,10],[11,12]])     # 3*2

c=torch.matmul(a,b)

print(c)

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [9]:
d=c+10

print(d)
print(torch.clamp(d,max=100))

tensor([[ 78,  84],
        [159, 174]])
tensor([[ 78,  84],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [ ]:
a=torch.tensor([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

print(torch.sum(a, dim=0))

tensor([55, 60, 65, 70, 75])
